"""Generate the Phase 1.5 results markdown from the IC table + quintile diagnostic."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from crv.config import Config


def _verdict(table: pd.DataFrame, quints: pd.DataFrame, tail_frac: float) -> str:
    """Honest read that reconciles rank-IC with the equal-weight long-short.

    The key Phase-1.5 finding is usually a divergence: positive rank IC (typical cheap
    bond converges) alongside a negative *mean* long-short (a distressed tail in the
    cheap bucket blows up). That divergence is the motivation for Phases 2-3, not a
    failure.
    """
    ic_ok = ((table["mean_ic"] > 0) & (table["t_stat"].abs() >= 2)).sum() >= 2
    ls_mean = quints.loc["LS", "mean_r"] if "LS" in quints.index else np.nan
    ls_med = quints.loc["LS", "median_r"] if "LS" in quints.index else np.nan

    if ic_ok and ls_mean < 0 <= ls_med:
        return (
            f"**GO for Phase 2 — with the central caveat made concrete.** Rank IC is "
            f"positive and HAC-significant at multiple horizons (the *typical* cheap bond "
            f"converges: monotone median returns, top-minus-bottom median LS = {ls_med:+.4f}). "
            f"But the equal-weight *mean* long-short is NEGATIVE ({ls_mean:+.4f}) because "
            f"~{tail_frac:.0%} of the cheapest bucket are distressed names with catastrophic "
            f"returns. The signal has genuine convergence content; an uncontrolled portfolio "
            f"loses to the distressed tail. This is exactly what Phase 2 (liquidity controls, "
            f"log-spread) and Phase 3 (default carry-through, contamination test, "
            f"neutralization) are built to fix."
        )
    if ic_ok and ls_mean >= 0:
        return ("**GO.** Positive HAC-significant IC and a positive equal-weight long-short even "
                "before controls — stronger than expected for a naive signal.")
    if (table["mean_ic"] > 0).all():
        return ("**WEAK/POSITIVE.** IC positive across horizons but not all HAC-significant; "
                "Phase 2's controlled signal should sharpen it.")
    return ("**FLAT/MIXED.** Naive signal lacks consistent positive IC — expected for an "
            "uncontrolled level-spread residual; motivates Phase 2 rather than condemning it.")


def write_phase1_5_summary(
    cfg: Config, table: pd.DataFrame, quints: pd.DataFrame, mid_horizon: int,
    tail_frac: float,
) -> Path:
    out = cfg.paths.docs / "phase1_5-results.md"
    lines = [
        "# Phase 1.5 — Thin Backtest Results (signal-content gate)",
        "",
        "> Auto-generated by `crv backtest`. Naive signal only: spread-return proxy outcome,",
        "> **no costs / neutralization / default handling** (those are Phase 3). The outcome is",
        "> a costless spread-change proxy off the same price series, so magnitudes are optimistic",
        "> (bid-ask bounce can inflate mean-reversion); treat as direction-of-travel, not P&L.",
        "",
        "## Information coefficient (rank IC, HAC SE, lag = horizon-1)",
        "",
        table.to_markdown(index=False, floatfmt=".4f"),
        "",
        f"## Quintile diagnostic ({mid_horizon}m, naive — no neutralization/costs)",
        "",
        quints.to_markdown(floatfmt=".5f"),
        "",
        "(Quantile 1 = richest, top = cheapest; **LS** = top − bottom. The mean-vs-median gap is",
        f"the contamination signal: ~{tail_frac:.0%} of the cheapest bucket has forward return",
        "< −5% — the distressed tail.)",
        "",
        "## Read",
        "",
        _verdict(table, quints, tail_frac),
        "",
        f"Figures: `reports/ic_decay.png`, `reports/ic_timeseries_{mid_horizon}m.png`.",
    ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    return out
